name: noteapp
description: A multi-user notes application with Supabase authentication.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  dotenv: ^4.1.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.5
  supabase_flutter: ^2.5.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true